# Generated by Django 4.1.4 on 2022-12-22 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cafe_core_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealclick',
            name='clicked_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('Hot meals', 'Hot Meals'), ('Drinks', 'Drink'), ('Dessert', 'Dessert'), ('NO_TYPE', 'No Type')], default='NO_TYPE', max_length=30),
        ),
        migrations.AlterField(
            model_name='meal',
            name='size',
            field=models.IntegerField(verbose_name='Вес блюда'),
        ),
    ]
